pipeline {
    agent any

    environment {
        REGISTRY_URL = "573368209887.dkr.ecr.us-east-1.amazonaws.com"
        IMAGE_TAG = "0.0.$BUILD_NUMBER"
        IMAGE_NAME = "youtube-bot"

    }

    stages {

        stage('Build Bot app') {
            steps {
                sh '''
                   aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REGISTRY_URL
                   docker build -t $IMAGE_NAME:$BUILD_NUMBER .
                   docker tag $IMAGE_NAME:$BUILD_NUMBER $REGISTRY_URL/$IMAGE_NAME:$BUILD_NUMBER
                   docker push $REGISTRY_URL/$IMAGE_NAME:$BUILD_NUMBER
                   '''
            }
            post {
                always {
                    sh '''
                    docker image prune -f --filter "label=app=bot"
                    '''
                }
            }
        }